#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example excerpt from SNMP data:
# .1.3.6.1.4.1.674.10893.2.31.500.1.1.0 = STRING: NAME
# .1.3.6.1.4.1.674.10893.2.31.500.1.2.0 = STRING: 0123456789abcdef0123456789abcdef
# .1.3.6.1.4.1.674.10893.2.31.500.1.4.0 = STRING: DELL
# .1.3.6.1.4.1.674.10893.2.31.500.1.5.0 = STRING: MD34xx
# .1.3.6.1.4.1.674.10893.2.31.500.1.6.0 = STRING: 2701
# .1.3.6.1.4.1.674.10893.2.31.500.1.7.0 = INTEGER: 1

def inventory_dell_mdss(info):
    for mdss in info:
        yield mdss[0], {}

def check_dell_mdss(item, params, info, timestamp=None):
    for mdss in info:
        name, wwid, vendor, product, model, attention = mdss

        if not name == item:
            continue

        yield 0, "{} {} {} (WWID: {})".format(vendor, product, model, wwid)

        if not saveint(attention) == 0:
            yield 1, "Needs Attention"

check_info["dell_mdss"] = {
    'inventory_function'    : inventory_dell_mdss,
    'check_function'        : check_dell_mdss,
    'service_description'   : 'MD %s',
    'snmp_info'             : ('.1.3.6.1.4.1.674.10893.2.31.500.1', [
        '1', # DELL-MD-SS-06-MIB::ssStorageArrayName.0
        '2', # DELL-MD-SS-06-MIB::ssStorageArrayWWID.0
        '4', # DELL-MD-SS-06-MIB::ssVendorID.0
        '5', # DELL-MD-SS-06-MIB::ssProductID.0
        '6', # DELL-MD-SS-06-MIB::ssModelName.0
        '7'  # DELL-MD-SS-06-MIB::ssStorageArrayNeedsAttention.0
    ]),
    'snmp_scan_function'    : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.674.10893.2.31"
}
